using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using GoLive.Generator.ApiClientGenerator.Data;
using GoLive.Generator.ApiClientGenerator.Generation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GoLive.Generator.ApiClientGenerator
{
    [Generator]
    public class ApiClientGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context) {
            context.RegisterPostInitializationOutput(ctx
                => ctx.AddSource(nameof(ApiClientGeneratorIgnoreAttribute), ApiClientGeneratorIgnoreAttribute));

            IncrementalValuesProvider<ControllerRoute> controllerDeclarations = context.SyntaxProvider
               .CreateSyntaxProvider(
                    predicate: static (s, _) => Scanner.CanBeController(s), 
                    transform: static (ctx, _) => GetControllerDeclarations(ctx))
               .Where(static c => c is not null)!;

            var configFiles = context.AdditionalTextsProvider.Where(IsConfigurationFile);
            var controllersAndConfig = controllerDeclarations.Collect().Combine(configFiles.Collect());
            context.RegisterSourceOutput(controllersAndConfig, 
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static ControllerRoute? GetControllerDeclarations(GeneratorSyntaxContext context)
        {
            // we know the node is a ClassDeclarationSyntax thanks to CanBeController
            var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;

            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax);
            return symbol is not null && Scanner.IsController(symbol) ? Scanner.ConvertToRoute(symbol) : null;
        }

        private static bool IsConfigurationFile(AdditionalText text)
            => text.Path.EndsWith("ApiClientGenerator.json");
        
        internal static void Execute(
            ImmutableArray<ControllerRoute> controllerRoutes,
            IEnumerable<AdditionalText> configurationFiles, SourceProductionContext context) 
        {
            RouteGeneratorSettings config = LoadConfig(configurationFiles) ?? new RouteGeneratorSettings();

            #if DEBUG

            string? directory = Path.GetDirectoryName(config.OutputFile)
                             ?? config.OutputFiles?.Select(Path.GetDirectoryName).FirstOrDefault(s => s is not null);
            string debugFile = directory is null ? "GeneratedRoutes.txt" : Path.GetFullPath(Path.Combine(directory, "GeneratedRoutes.txt"));
            File.WriteAllLines(debugFile,
                controllerRoutes.Select(r
                    => $"{r.Area}/{r.BaseRoute}/{r.Name} [{string.Join(",\n\t", r.Actions.Select(a => $"{(a.IsAsync ? "async " : null)}{a.ReturnTypeName ?? "Void"} {a.Name} {a.Method}"
                    + $" ({string.Join(", ", a.ServerParameters.Select(p => (p.IsService ? "[FromServices] " : null) + $"{p.FullTypeName} {p.Name}"))})"))}]"));

            #endif

            var source = new SourceStringBuilder();

            if (config.PreAppendLines is { Count: > 0 })
            {
                config.PreAppendLines.ForEach(source.AppendLine);
            }
            
            source.AppendLine("using System.Net.Http;");
            source.AppendLine("using System.Threading.Tasks;");
            source.AppendLine("using System.Net.Http.Json;");
            source.AppendLine("using System.Text.Json;");
            source.AppendLine("using System.Collections.Generic;");
            source.AppendLine("using System.Threading;");
            source.AppendLine("using System.Diagnostics.CodeAnalysis;");

            if (config.UseResponseWrapper)
            {
                source.AppendLine("using System.Net;");
            }

            if (config.Includes != null && config.Includes.Any())
            {
                foreach (var s in config.Includes)
                {
                    source.AppendLine($"using {s};");
                }
            }

            source.AppendLine();

            source.AppendLine(!string.IsNullOrWhiteSpace(config.Namespace)
                ? $"namespace {config.Namespace};"
                : "namespace AutogeneratedClient;");

            var orderedControllerRoutes = controllerRoutes
                                         .OrderBy(r => r.Name)
                                         .ToArray();

            SetUpApiClient(config, orderedControllerRoutes, source);

            var clientGenerator = new ClientGenerator(config, source, new HttpActionGenerator(config, source));

            foreach (ControllerRoute? route in orderedControllerRoutes)
                clientGenerator.Generate(route);

            if (config.GenerateInterface)
                GenerateApiClientInterface(config, orderedControllerRoutes, source);

            if (config.PostAppendLines is { Count: > 0 })
            {
                config.PostAppendLines.ForEach(source.AppendLine);
            }

            if ((string.IsNullOrWhiteSpace(config.OutputFile) && (config.OutputFiles == null || config.OutputFiles.Count == 0)))
            {
                context.AddSource("GeneratedApiClient", source.ToString());
            }
            else
            {
                SaveSourceToFile(config, source);
            }

            if (config.GenerateServerImplementation) {
                source.Clear();
                GenerateServerImplementation(config, orderedControllerRoutes, source);
                context.AddSource("ServerApiClientImplementation.g.cs", source.ToString());
            }
        }

        private static void SaveSourceToFile(RouteGeneratorSettings config, SourceStringBuilder source)
        {
            var content = source.ToString();
            if (config.OutputFiles is { Count: > 0 })
            {
                foreach (var configOutputFile in config.OutputFiles)
                {
                    File.WriteAllText(configOutputFile, content);
                }
            }
            else
            {
                File.WriteAllText(config.OutputFile!, content);
            }
        }

        private static RouteGeneratorSettings? LoadConfig(IEnumerable<AdditionalText> configFiles)
        {
            AdditionalText? configFilePath = configFiles.FirstOrDefault();

            if (configFilePath == null)
                return null;

            var jsonString = File.ReadAllText(configFilePath.Path);
            var config = JsonSerializer.Deserialize<RouteGeneratorSettings>(jsonString)!;
            var configFileDirectory = Path.GetDirectoryName(configFilePath.Path)!;

            if (config.OutputFile is not null) {
                var fullPath = Path.Combine(configFileDirectory, config.OutputFile);
                config.OutputFile = Path.GetFullPath(fullPath);
            }

            if (config.OutputFiles != null && config.OutputFiles.Count > 0)
            {
                config.OutputFiles = config.OutputFiles.Select(e => Path.GetFullPath(Path.Combine(configFileDirectory, e))).ToList();
            }

            return config;
        }

        private static void GenerateApiClientInterface(RouteGeneratorSettings config, IReadOnlyCollection<ControllerRoute> routes, SourceStringBuilder source) {
            source.AppendLine();
            source.AppendLine("public partial interface IApiClient");
            source.AppendOpenCurlyBracketLine();

            foreach (ControllerRoute route in routes)
            {
                source.AppendLine();
                source.AppendLine($"I{ClientGenerator.ClientClassName(route)} {ClientGenerator.ClientPropertyName(route)} {{ get; }}");
            }

            source.AppendCloseCurlyBracketLine();

            var interfaceGenerator =
                new ClientInterfaceGenerator(config, source, new ActionInterfaceGenerator(config, source));
            foreach (ControllerRoute route in routes) {
                interfaceGenerator.Generate(route);
            }
        }

        private static void GenerateServerImplementation(RouteGeneratorSettings config, IReadOnlyCollection<ControllerRoute> routes, SourceStringBuilder source) {
            if (config.GenerateInterface)
                source.AppendLine($"using {config.Namespace ?? "AutogeneratedClient"};");

            source.AppendLine($$"""
                #nullable enable
                
                using System;
                using System.Net;
                using System.Threading.Tasks;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.AspNetCore.Mvc;
                
                namespace {{config.ServerImplementationNamespace ?? "GeneratedImplementation"}};
                
                public partial class ServerApiClientImplementation{{(config.GenerateInterface ? " : IApiClient" : null)}}
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly IServiceScopeFactory _scopeFactory;
                    
                    public ServerApiClientImplementation(IServiceProvider serviceProvider, IServiceScopeFactory scopeFactory)
                    {
                        _serviceProvider = serviceProvider;
                        _scopeFactory = scopeFactory;
                    }
                """);

            source.IndentLevel = 1;

            foreach (ControllerRoute route in routes)
            {
                source.AppendLine();
                source.AppendLine($"private I{ClientGenerator.ClientClassName(route)}? _field{ClientGenerator.ClientPropertyName(route)};");
                source.AppendLine($"public I{ClientGenerator.ClientClassName(route)} {ClientGenerator.ClientPropertyName(route)}");
                source.AppendLine($"    => _field{ClientGenerator.ClientPropertyName(route)} ??= new {ImplementationGenerator.ImplementationClassName(route)}(this);");
            }

            source.AppendLine($$"""
                
                    internal AsyncServiceScope GetScope()
                        => _scopeFactory.CreateAsyncScope();
                        
                    internal TController CreateController<TController>(IServiceProvider services) where TController : ControllerBase {
                        var controller = services.GetRequiredService<TController>();
                        InitializeController(controller);
                        return controller;
                    }
                    
                    partial void InitializeController(ControllerBase controller);
                    
                    internal partial bool CanHandleException(Exception exception);
                    
                    internal partial {{(config.UseResponseWrapper ? config.ResponseWrapperType : "void")}} HandleException(Exception exception);
                    internal partial {{(config.UseResponseWrapper ? $"{config.ResponseWrapperType}<T>" : "T")}} HandleException<T>(Exception exception);
                    
                """, indent: false);
            if (config.UseResponseWrapper) {
                source.AppendLine($"""
                    internal partial {config.ResponseWrapperType} CreateWrapper();
                    internal partial {config.ResponseWrapperType}<T> WrapResult<T>(T result);
                    
                """, indent: false);
            }

            if (config.ServerImplementationTransformParameterTypes is { } types) {
                foreach (string type in types) {
                    source.AppendLine($"internal partial ValueTask<{type}> TransformAsync({type} value);");
                }
            }

            source.AppendCloseCurlyBracketLine();

            var implementationGenerator =
                new ImplementationGenerator(config, source, new ServerImplementationActionGenerator(config, source));
            foreach (ControllerRoute route in routes) {
                implementationGenerator.Generate(route);
            }
        }

        private static void SetUpApiClient(RouteGeneratorSettings config, IReadOnlyCollection<ControllerRoute> routes, SourceStringBuilder source)
        {
            source.AppendLine();
            source.AppendLine($"public partial class ApiClient{(config.GenerateInterface ? " : IApiClient" : null)}");
            source.AppendOpenCurlyBracketLine();

            source.AppendLine("public ApiClient(HttpClient client)");
            source.AppendOpenCurlyBracketLine();

            foreach (ControllerRoute route in routes)
            {
                source.AppendLine($"{ClientGenerator.ClientPropertyName(route)} = new {ClientGenerator.ClientClassName(route)}(client);");
            }

            source.AppendCloseCurlyBracketLine();
            
            string? iPrefix = config.GenerateInterface ? "I" : null;
            foreach (ControllerRoute route in routes)
            {
                source.AppendLine();
                source.AppendLine($"public {iPrefix}{ClientGenerator.ClientClassName(route)} {ClientGenerator.ClientPropertyName(route)} {{ get; }}");
            }

            source.AppendCloseCurlyBracketLine();
            
            if (config.IncludeResponseWrapper)
            {
                source.AppendLine();
                source.AppendLine($"public class {config.ResponseWrapperType}");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine($"public {config.ResponseWrapperType}() {{}}");
                source.AppendLine($"public {config.ResponseWrapperType}(HttpStatusCode statusCode)");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("StatusCode = statusCode;");
                source.AppendCloseCurlyBracketLine();
                source.AppendLine("public HttpStatusCode StatusCode { get; }");
                source.AppendLine("public bool Success => (int)StatusCode >= 200 && (int)StatusCode <= 299;");
                source.AppendMultipleLines($$"""
                    public static async Task<{{config.ResponseWrapperType}}> FromResponseTask(Task<HttpResponseMessage> responseTask) {
                        using HttpResponseMessage message = await responseTask;
                        return new(message.StatusCode);
                    }
                    """);
                source.AppendCloseCurlyBracketLine();

                source.AppendLine();
                source.AppendLine($"public class {config.ResponseWrapperType}<T> : {config.ResponseWrapperType}");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine($"public {config.ResponseWrapperType}() {{}}");
                source.AppendLine($"public {config.ResponseWrapperType}(HttpStatusCode statusCode, T? data) : base(statusCode)");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("Data = data;");
                source.AppendCloseCurlyBracketLine();
                source.AppendMultipleLines("""
                    public T? Data { get; }

                    public T SuccessData => Success ? Data ?? throw new NullReferenceException("Response had an empty body!")
                                                    : throw new InvalidOperationException("Request was not successful!");
                    """);
                source.AppendLine("public bool TryGetSuccessData([NotNullWhen(true)] out T? data)");
                source.AppendOpenCurlyBracketLine();
                source.AppendLine("data = Data;");
                source.AppendLine("return Success && data is not null;");
                source.AppendCloseCurlyBracketLine();
                source.AppendMultipleLines($$"""
                    public static async Task<{{config.ResponseWrapperType}}<T>> FromResponseTask(
                        Task<HttpResponseMessage> responseTask, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default) {
                        using HttpResponseMessage message = await responseTask;
                        return new(message.StatusCode, 
                            await (message.Content?.ReadFromJsonAsync<T>(options, cancellationToken: cancellationToken)
                            ?? Task.FromResult<T?>(default)));
                    }
                    """);
                source.AppendCloseCurlyBracketLine();
            }
        }

        private const string ApiClientGeneratorIgnoreAttribute = """
             namespace ApiClientGenerator
             {
                 public class ApiClientGeneratorIgnoreAttribute : System.Attribute { }
             }
             """;

        public const string ApiClientGeneratorIgnoreAttributeNamespace = "ApiClientGenerator.ApiClientGeneratorIgnoreAttribute";
    }
}